# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=234)),
                ('year', models.CharField(max_length=111)),
                ('charge_id', models.CharField(max_length=234)),
            ],
        ),
    ]
